version: "3.9"
services:
  web1:
    build: .
    image: "web_app:1.0"
      
  web2:
    build: .
    image: "web_app:2.0"

  proxy:
    build: ./Docker/proxy
    image: proxy_server
    ports: 
      - 80:80

